# OCP Console Embed configuration
ocpConsoleEmbed:
  namespace: ocp-console-embed
  name: ocp-console-embed
  image: quay.io/openshift/origin-cli:latest

# Injected by parent chart
deployer:
  domain: ""
