# OCP Console Embed configuration
ocpConsoleEmbed:
  namespace: ocp-console-embed
  name: ocp-console-embed
  image: quay.io/openshift/origin-cli:4.17

# Injected by parent chart
deployer:
  domain: ""
  guid: ""
  numUsers: 0
